### ISSUE TITLE
Dokumentation erstellen/updaten

### ISSUE THREAD

**Issue by Akaime93** [kohloderso/fitInnsbruckApp#2]
Readme-Datei von Github updaten (aktuellere Beschreibung) mit folgenden Punkten:
- Beschreibung der App (für was man diese App braucht und was sie kann usw.)
- Zielgruppen definieren für die, die App ausgelegt ist
- Links zu Mockups
- Vorraussetzungen für bestimmte Funktionen (GPS usw.)
- wie kann man die App benutzen? (Heroku Link + kurze Erklärung wie man sie lokal kompilieren kann)

**Comment by BlueBabyYoshi** [comment]
Um auch für die nächste Grippewelle und eventuelle Babypausen von Mitarbeiterinnen gewappnet zu sein und das Projekt ohne Probleme weiterführen und spätre ausbauen zu können, verlangt CEO Hans Tryndamere eine anständige Dokumentation.

**Comment by kohloderso** [comment]
http://www.lesscode.de/initiative/readme-vor-code/
Schöne Erklärung wie man das richtig macht

**Comment by kohloderso** [comment]
Also erstens: Eine kurze Beschreibung was das System kann:
Fit in Innsbruck ist eine Webapplikation, die sportbegeisterten Menschen helfen kann, geeignete Orte (vorerst nur in Innsbruck) zu finden, um ihrer Leidenschaft nachgehen zu können.

**Comment by kohloderso** [comment]
Funktionen:
- Benutzerverwaltung (Registrierung/Login/Logout)
- Speichern vergangener Aktivitäten
- Suchen nach Sportstätten anhand unterschiedlicher Kriterien:
  - Sportart
  - Öffnungszeiten
  - Preis
  - Location
  - Wetter
- Detaillierte Beschreibung der Sportstätte
- Berechnung der Route vom aktullen (oder einem gewählten) Standpunkt zur Sportstätte
- Verwalten von Sportstätten

**Comment by kohloderso** [comment]
Installation:
Eine aktuelle Version der App kann über Heroku geöffnet werden. Dazu muss man in einem beliebigen Browser nur diesen Link aufrufen: http://fit-in-innsbruck.herokuapp.com/
Wer die App lokal benutzen möchte, kann sich auch den in diesem Repository befindlichen source-code herunterladen und selbst kompilieren. Dazu benötigt man zumindest Java 1.8 sowie das Play Framework [1] in der Version 2.2. 
Hat man alles heruntergeladen, wechselt man über die Kommandozeile in den fitInnsbruck-Ordner. Hier muss man nur noch activator run eingeben und die App wird kompiliert und auf einem lokalen Server gestartet. Aufrufen kann man sie dann, indem man in einem beliebigen Browser localhost:9000 eingibt.
[1] https://www.playframework.com/

Bei dem installationszeugs wären zur Erklärung ein paar Bilder fein!

**Comment by kohloderso** [comment]
minimale Vorraussetzungen:
- Browser
- funktionierende Internetverbindung
- Standortzugriff muss möglich sein (braucht man aber nur für Routen)

**Comment by kohloderso** [comment]
Verwendung:
Wir haben uns sehr viel Mühe gegeben, die App so benutzerfreundlich wie möglich zu gestalten und sind der Meinung, dass keine weitere Erklärung notwendig ist, um sie zu verwenden. Die eingebauten Funktionen sind selbsterklärend. Sobald wir ausgefeiltere Features hinzufügen werden wir diesen Abschnitt ergänzen.

**Comment by kohloderso** [comment]
FAQ:
Wird im Bedarfsfall ergänzt.

**Comment by kohloderso** [comment]
sehr praktisch zum Readme schöner gestalten: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
