### ISSUE TITLE
Klassendiagramm

### ISSUE THREAD

**Issue by kohloderso** [kohloderso/fitInnsbruckApp#3]
- Klassendiagramm der App erstellen, so wie sie momentan aussieht
- dieses Diagramm so ergänzen, dass die gewünschten zusätzlichen Features berücksichtigt werden
  Das sind Öffnungszeiten, Preise, Standort und Routen, Speichern von Aktivitäten

**Comment by BlueBabyYoshi** [comment]
Um während des Projekts den Überblick über die Funktionen und Features nicht zu verlieren, schlägt Praktikantin Ashe Vayne vor ein Klassendiagramm zu erstellen und dieses auch wenn nötig auszubauen.

**Comment by kohloderso** [comment]
![uml](https://cloud.githubusercontent.com/assets/10177705/6953127/74d545c6-d8c7-11e4-8d31-4d6889180f84.JPG)
Die Frage ist jetzt noch, ob wir die Views auch mit reinnehmen wollen.

**Comment by kohloderso** [comment]
![uml_betterscaling](https://cloud.githubusercontent.com/assets/10177705/6953234/48519b02-d8c8-11e4-8ac8-18119a84a860.jpg)
nochmal in besserer Auflösung

**Comment by kohloderso** [comment]
![uml](https://cloud.githubusercontent.com/assets/10177705/7048035/9063355c-de10-11e4-9826-e6d2a1445bd6.JPG)
hab die views jetzt auch noch dazugenommen. Könnte ja ganz praktisch sein, die auch übersichtlich drinzuhaben.

**Comment by kohloderso** [comment]
Hab die views jetzt auch noch mit reingenommen. Könnte ja ganz die praktisch sein, die auch übersichtlich drinzuhaben.
![uml](https://cloud.githubusercontent.com/assets/10177705/7048134/4c0be3f8-de11-11e4-8a84-c656116dd283.JPG)

**Comment by kohloderso** [comment]
neuere, etwas besser verständliche Version (minimale Unterschiede)
![uml_betterscaling](https://cloud.githubusercontent.com/assets/10177705/7215089/3ef26ef4-e5c7-11e4-97ee-c1543df44c24.jpg)
