### ISSUE TITLE
CSV-File vorbereiten

### ISSUE THREAD

**Issue by chantalchantalchantal** [kohloderso/fitInnsbruckApp#4]
- Duplikate eliminieren im csv-File(z.b Sportstätten öfter drinnen)
- Öffnungszeiten und Preise Spalte hinzufügen
- Es soll eine weitere Spalte hinzugefügt werden für jeden Wochentag und soll die Form haben : "HH:MM-HH:MM, HH:MM-HH:MM".
  Mehrere Öffnungszeiten an einem Tag werden mit Beistrichen getrennt und die Wochentage durch Strichpunkte. Ruhetage werden mit "null" gekennzeichnet und ganztägig geöffnete Sportstätten mit "00:00-24:00"
- In einer weiteren Spalte soll der Preis für Kinder und Erwachsene stehen und muss die Form:"X,YZ" haben

**Comment by BlueBabyYoshi** [comment]
Tom der Sohn von Ashe jammert immer das er nie genau weiß wann das Schwimmbad,Hallenbad oder der Fußballplatz geöffnet haben, was Ashe auf die Idee bringt nicht nur den Ort sondern auch Öffnungszeiten und weiters Preise in der App anzeigen zu lassen, damit sie auch noch weiß wieviel Geld sie ihrem Sohn mitgeben sollte.

**Comment by kohloderso** [comment]
Nach reiflicher Überlegung haben wir beschlossen, den Schritt mit dem File auslesen nun ganz auszulassen und gleich die Datenbank zu befüllen. Die Sportstätten lassen sich dadurch viel leichter verwalten. Siehe neuer Issue: https://github.com/kohloderso/fitInnsbruckApp/issues/7
